{
	"version": 1484919162,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/sprite-sheet0.png",
		"images/spritefont.png",
		"images/sprite2-sheet0.png",
		"images/sprite2-sheet1.png",
		"images/sprite2-sheet2.png",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/tilemap.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"media/hit_mark-metallic-9040_hifi.m4a",
		"media/hit_mark-metallic-9040_hifi.ogg",
		"media/nexus - pain and darkness.m4a",
		"media/nexus - pain and darkness.ogg",
		"media/nuxus v1.m4a",
		"media/nuxus v1.ogg",
		"media/nexus - once upon a nexus story.m4a",
		"media/nexus - once upon a nexus story.ogg",
		"media/epic cinematic musicno copyright free music.m4a",
		"media/epic cinematic musicno copyright free music.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"title.ttf",
		"font.css"
	]
}